server:
    port: 40000
    tomcat:
        uri-encoding: utf-8
spring:
    datasource:
        url: jdbc:mysql://localhost/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        username: root
        password:
        driver-class: com.mysql.jdbc.Driver
    jpa:
        show-sql: true
        database: mysql