server:
    port: 9300
eureka:
    instance:
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 10
    client:
        fetch-registry: false
        register-with-eureka: false
        registry-fetch-interval-seconds: 5
        service-url:
            defaultZone: http://localhost:7788/eureka/
spring:
    application:
        name: service-demo
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
        username: demo
        password: Demo#123456
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
            idle-timeout: 30000
            minimum-idle: 5
            maximum-pool-size: 15
            pool-name: TownmcHikariCP
            max-lifetime: 1800000
            connection-timeout: 30000
            connection-test-query: SELECT 1
            connection-init-sql: set names utf8mb4
            validation-timeout: 5000
    jpa:
        show-sql: true
        database: mysql
    redis:
        host: 127.0.0.1
        password: admin123456
        port: 6379
        database: 6
        timeout: 1000
    rabbitmq:
        host: 127.0.0.1
        port: 5672
        username: dev
        password: dev
        virtual-host: /dev
    # 需要做邮件发送是配置
    #    mail:
    #        host: smtp.exmail.qq.com
    #        username: sender@example.com
    #        password: 123456
    #        default-encoding: UTF-8
    #        properties:
    #            mail:
    #                smtp:
    #                    ssl:
    #                        enable: true
    #                    auth: true
    #                    starttls:
    #                        enable: true
    #                        required: true
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
mybatis:
    #mapper配置文件
    mapper-locations: classpath:com/townmc/boot/dao/mybatis/*.xml
    #开启驼峰命名
    configuration:
        map-underscore-to-camel-case: true
pagehelper:
    helper-dialect: mysql
logging:
    level:
        root: INFO
        com.townmc: DEBUG
swagger:
    enable: true
    test-auth: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJpc3MiLCJpZCI6IjEwMDAiLCJ0aW1lIjoiMTYzMTAwMzg0NyJ9.KuUPrxLD59Xs35GCFE4xlH30vQ4BN8mOzoQR99QnZrA
scheduling:
    enabled:
        demo: false
performance-stat: true
## 测试环境
ribbon:
    # 负载均衡不使用eureka
    eureka:
        enabled: false
    # 关闭断路器
    hystrix:
        enabled: false
