server:
    port: 40000
    tomcat:
        uri-encoding: utf-8
spring:
    datasource:
        url: jdbc:mysql://1.1.1.1/test?useUnicode=true&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
            idle-timeout: 30000
            minimum-idle: 5
            maximum-pool-size: 15
            pool-name: DatebookHikariCP
            max-lifetime: 1800000
            connection-timeout: 30000
    jpa:
        show-sql: true
        database: mysql
    redis:
        host: localhost
        password: 123456
        port: 6379
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
        joda-date-time-format: yyyy-MM-dd HH:mm:ss
logging:
    level:
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE
        com.townmc: debug